// Product catalog for Armani Esso store
export interface ProductVariant {
  id: string;
  name: string;
  value: string;
  sku?: string;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  category: 'branding' | 'stationery' | 'apparel' | 'displays' | 'gifts';
  image: string;
  printSize: string;
  isOnSale?: boolean;
  sku?: string;
  variants?: ProductVariant[]; // e.g., [{ id: 'color', name: 'Color', value: 'Red', sku: 'RED-1' }]
  customization?: {
    allowText?: boolean;
    allowDesign?: boolean;
    maxCharacters?: number;
  };
}

export const categories = [
  { id: 'displays', name: 'Displays & Banners' },
  { id: 'stationery', name: 'Stationery & Business' },
  { id: 'branding', name: 'Branding & Apparel' },
  { id: 'gifts', name: 'Gifts & Accessories' },
] as const;

export const products: Product[] = [
  {
    id: '1-x-1m-flags',
    name: '1 x 1m Flags',
    description: 'Compact branded flags for outdoor visibility and event promotions.',
    price: 350,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-8-800x800.png',
    printSize: '1m x 1m',
  },
  {
    id: '100-a3-calendars',
    name: '100 A3 Calendars',
    description: 'Custom A3 calendars for corporate gifting and year-round branding.',
    price: 1500,
    category: 'stationery',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-25-800x800.png',
    printSize: 'A3',
  },
  {
    id: '100-a5-diaries',
    name: '100 A5 Diaries',
    description: 'Branded A5 diaries for offices, clients, and executive gifts.',
    price: 1200,
    category: 'stationery',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/Advantage-A5-2022-Diary-Blue-1-800x800.jpg',
    printSize: 'A5',
  },
  {
    id: '100-a5-flyers',
    name: '100 A5 Flyers',
    description: 'Affordable A5 flyers for campaigns, specials, and event handouts.',
    price: 300,
    category: 'stationery',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-21-800x800.png',
    printSize: 'A5',
  },
  {
    id: '100-custom-lanyards',
    name: '100 Custom Lanyards',
    description: 'Custom lanyards for staff, conferences, and visitor passes.',
    price: 1500,
    category: 'stationery',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-24-800x800.png',
    printSize: 'Standard',
  },
  {
    id: '100-double-sided-business-cards-350gsm',
    name: '100 Double-Sided Business Cards (350gsm)',
    description: 'Premium double-sided business cards printed on thick 350gsm stock.',
    price: 400,
    category: 'stationery',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-1-1-800x800.png',
    printSize: '350gsm',
  },
  {
    id: '100-event-tickets',
    name: '100 Event Tickets',
    description: 'Custom printed tickets for launches, raffles, and events.',
    price: 350,
    category: 'stationery',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-13-800x800.png',
    printSize: 'Ticket size',
  },
  {
    id: '100-one-sided-business-cards-350gsm',
    name: '100 One-Sided Business Cards (350gsm)',
    description: 'Simple one-sided business cards on premium 350gsm stock.',
    price: 250,
    category: 'stationery',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-3-1-800x800.png',
    printSize: '350gsm',
  },
  {
    id: '16-custom-designed-sports-kits-including-printing',
    name: '16 Custom Designed Sports Kits (Including Printing)',
    description: 'Complete custom sports kit package with printing included.',
    price: 8000,
    category: 'apparel',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-16-800x800.png',
    printSize: 'Full kit',
  },
  {
    id: '2m-x-600m-telescopic-flag',
    name: '2m x 600m Telescopic Flag',
    description: 'Tall telescopic flag setup for roadshow and outdoor branding.',
    price: 700,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-9-800x800.png',
    printSize: '2m x 600m',
  },
  {
    id: 'a4-back-front-embroidery-printing',
    name: 'A4 Back & Front Embroidery Printing',
    description: 'Front and back embroidery printing for branded apparel and uniforms.',
    price: 85,
    originalPrice: 90,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2020/10/A4-3-800x800.png',
    printSize: 'A4',
    isOnSale: true,
  },
  {
    id: 'a4-back-front-screen-printing',
    name: 'A4 Back & Front Screen Printing',
    description: 'A4 screen printing on both sides for workwear and branded apparel.',
    price: 75,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/A4-5-800x800.png',
    printSize: 'A4',
  },
  {
    id: 'a4-dtf-printing-on-caps',
    name: 'A4 DTF Printing on Caps',
    description: 'Direct-to-film cap printing for crisp, colourful branding.',
    price: 40,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/2-800x800.png',
    printSize: 'Caps',
  },
  {
    id: 'a4-embroidery-printing',
    name: 'A4 Embroidery printing',
    description: 'Embroidery printing for professional branding and uniforms.',
    price: 65,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/c597c50a-7ef6-4136-9781-ee6754dfd1be-800x800.jpeg',
    printSize: 'A4',
  },
  {
    id: 'a4-embroidery-printing-on-caps',
    name: 'A4 Embroidery Printing on Caps',
    description: 'Cap embroidery printing for branded headwear and promotions.',
    price: 45,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/4-800x800.png',
    printSize: 'Caps',
  },
  {
    id: 'a4-screen-printing-standard',
    name: 'A4 Screen Printing',
    description: 'Reliable A4 screen printing for everyday branding needs.',
    price: 55,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2020/10/t-shirt-5.jpg',
    printSize: 'A4',
  },
  {
    id: 'a4-screen-printing-tshirt-three',
    name: 'A4 Screen Printing',
    description: 'Screen printing on apparel with a clean, high-contrast finish.',
    price: 55,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2020/10/t-shirt-03.jpg',
    printSize: 'A4',
  },
  {
    id: 'a4-screen-printing-tshirt-four',
    name: 'A4 Screen Printing',
    description: 'Screen printing with a discounted sale price for apparel branding.',
    price: 55,
    originalPrice: 60,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2020/10/t-shirt-04.jpg',
    printSize: 'A4',
    isOnSale: true,
  },
  {
    id: 'a4-screen-printing-on-caps',
    name: 'A4 Screen Printing on Caps',
    description: 'Screen printing for caps and small-format branded accessories.',
    price: 45,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/3-800x800.png',
    printSize: 'Caps',
  },
  {
    id: 'back-and-front-a4-screen-printing',
    name: 'Back and Front A4 Screen Printing',
    description: 'Back and front screen printing for branded garments and uniforms.',
    price: 80,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/A4-1-800x800.png',
    printSize: 'A4',
  },
  {
    id: 'ball-pens-supply-and-print-1-to-50-pieces',
    name: 'Ball Pens (Supply and Print) 1 to 50 Pieces',
    description: 'Printed ball pens for giveaways, offices, and promotional packs.',
    price: 20,
    category: 'stationery',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-6-800x800.png',
    printSize: '1 to 50 pieces',
  },
  {
    id: 'custom-key-holders',
    name: 'Custom Key Holders',
    description: 'Branded key holders for promo packs and corporate gifting.',
    price: 25,
    category: 'gifts',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-22-800x800.png',
    printSize: 'Standard',
  },
  {
    id: 'executive-pull-up-banner',
    name: 'Executive Pull-Up Banner',
    description: 'Premium pull-up banner for presentations, conferences, and retail spaces.',
    price: 1300,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-10-800x800.png',
    printSize: 'Large format',
  },
  {
    id: 'gazebos',
    name: 'Gazebos',
    description: 'Branded gazebo structures for markets, outdoor activations, and events.',
    price: 6000,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/07/7-800x800.png',
    printSize: 'Event canopy',
  },
  {
    id: 'matric-jacket-embroidery-printing',
    name: 'Matric Jacket Embroidery Printing',
    description: 'Embroidery printing for matric jackets and school celebration wear.',
    price: 250,
    category: 'apparel',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-14-800x800.png',
    printSize: 'Jackets',
  },
  {
    id: 'name-badges',
    name: 'Name Badges',
    description: 'Professional name badges for offices, events, and retail teams.',
    price: 35,
    category: 'stationery',
    image: 'https://etooprinters.co.za/wp-content/uploads/2020/10/badge.jpg',
    printSize: 'Badge',
  },
  {
    id: 'personalized-mugs-standard',
    name: 'Personalized Mugs',
    description: 'Custom printed mugs for branding, gifting, and everyday use.',
    price: 45,
    category: 'gifts',
    image: 'https://etooprinters.co.za/wp-content/uploads/2020/10/mug-01.jpg',
    printSize: 'Standard mug',
  },
  {
    id: 'personalized-mugs-sale',
    name: 'Personalized Mugs',
    description: 'Special offer on custom mugs for bulk branding and gifts.',
    price: 45,
    originalPrice: 50,
    category: 'gifts',
    image: 'https://etooprinters.co.za/wp-content/uploads/2020/10/mug-02.jpg',
    printSize: 'Standard mug',
    isOnSale: true,
  },
  {
    id: 'phone-case',
    name: 'Phone Case',
    description: 'Printed phone cases for personalised gifts and promotional branding.',
    price: 65,
    originalPrice: 90,
    category: 'gifts',
    image: 'https://etooprinters.co.za/wp-content/uploads/2020/10/case.jpg',
    printSize: 'Phone size',
    isOnSale: true,
  },
  {
    id: 'pocket-size-and-a4-embroidery-printing',
    name: 'Pocket Size and A4 Embroidery Printing',
    description: 'Embroidery printing in pocket and A4 sizes for branded apparel.',
    price: 85,
    originalPrice: 100,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-800x800.png',
    printSize: 'Pocket & A4',
    isOnSale: true,
  },
  {
    id: 'pocket-size-embroidery-printing',
    name: 'Pocket Size Embroidery Printing',
    description: 'Compact embroidery printing for small garment placements.',
    price: 45,
    originalPrice: 50,
    category: 'branding',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-1-800x800.png',
    printSize: 'Pocket size',
    isOnSale: true,
  },
  {
    id: 'pop-up-banner',
    name: 'Pop-Up Banner',
    description: 'Portable pop-up banner display for fast setup and strong visibility.',
    price: 1200,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/07/6-800x800.png',
    printSize: 'Large format',
  },
  {
    id: 'pull-up-banner',
    name: 'Pull Up Banner',
    description: 'Roll-up banner with sale pricing for events and retail displays.',
    price: 1000,
    originalPrice: 1200,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/07/4-800x800.png',
    printSize: 'Large format',
    isOnSale: true,
  },
  {
    id: 'tear-drop-banner',
    name: 'Tear Drop Banner',
    description: 'Tear drop banner ideal for outdoor activation and street visibility.',
    price: 800,
    originalPrice: 900,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/07/2-800x800.png',
    printSize: 'Large format',
    isOnSale: true,
  },
  {
    id: 'uv-screen-and-dtf-printing-on-umbrellas',
    name: 'UV, Screen, and DTF Printing on Umbrellas',
    description: 'Custom umbrella printing for promotions, gifts, and branded kits.',
    price: 45,
    category: 'gifts',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-5-800x800.png',
    printSize: 'Umbrellas',
  },
  {
    id: 'wall-banner',
    name: 'Wall Banner',
    description: 'Large wall banner for storefronts, activations, and backdrop branding.',
    price: 3500,
    originalPrice: 4000,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/07/5-800x800.png',
    printSize: 'Large format',
    isOnSale: true,
  },
  {
    id: 'x-banner-1-6-x-600m-standard',
    name: 'X-Banner (1.6 x 600m)',
    description: 'Compact X-banner display for exhibitions and retail promotions.',
    price: 750,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-18-800x800.png',
    printSize: '1.6 x 600m',
  },
  {
    id: 'x-banner-1-6-x-600m-alt',
    name: 'X-Banner (1.6 x 600m)',
    description: 'Alternative 1.6 x 600m X-banner listing with the same display format.',
    price: 600,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-7-800x800.png',
    printSize: '1.6 x 600m',
  },
  {
    id: 'x-banner-1-8-x-650m',
    name: 'X-Banner (1.8 x 650m)',
    description: 'Large-format X-banner for premium indoor and outdoor displays.',
    price: 750,
    category: 'displays',
    image: 'https://etooprinters.co.za/wp-content/uploads/2024/08/POCKETSIZE-4-800x800.png',
    printSize: '1.8 x 650m',
  },
];
